services:
  tinyml:
    environment:
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:64"
    command: >
      bash -lc "
        python data/prepare_tinystories.py &&
        python setup_cuda.py build_ext --inplace &&
        pytest -q &&
        python train.py
          --data tinystories
          --steps 1200
          --batch_size 8
          --seq_len 192
          --dim 384
          --n_layers 6
          --n_heads 6
          --lr 3e-4
          --compile &&
        python infer.py --ckpt out/best.pt --prompt 'Once upon a time' --max_new_tokens 80
      "
