name: muon_quick

# Use Muon optimizer
optimizer: muon

# Muon hyperparameters (slightly aggressive for quick tests)
muon_lr: 0.02
muon_momentum: 0.9
muon_nesterov: false
muon_ns_steps: 5
muon_orth_every: 2  # More frequent orthogonalization for short runs

# Weight decay
weight_decay: 0.0

# Base LR for scheduler
lr: 0.02
betas: [0.9, 0.95]

# Quick test settings
steps: 200
batch_size: 16
seq_len: 128

# Learning rate schedule
lr_schedule: cosine
warmup_steps: 20
min_lr_ratio: 0.1

# Gradient handling
grad_clip: 1.0
grad_accum_steps: 1

# Mixed precision (disabled for CPU compatibility)
mixed_precision: false

# Early stopping
early_stopping_patience: 0
early_stopping_min_delta: 0.01
