name: muon_long

# Use Muon optimizer
optimizer: muon

# Muon hyperparameters (conservative for long training stability)
muon_lr: 0.01
muon_momentum: 0.95
muon_nesterov: false
muon_ns_steps: 5
muon_orth_every: 8  # Less frequent for efficiency on long runs

# Weight decay (light regularization for long training)
weight_decay: 0.01

# Base LR for scheduler
lr: 0.01
betas: [0.9, 0.95]

# Long training settings
steps: 50000
batch_size: 32
seq_len: 512

# Learning rate schedule (longer warmup for stability)
lr_schedule: cosine
warmup_steps: 500
min_lr_ratio: 0.05

# Gradient handling
grad_clip: 1.0
grad_accum_steps: 2

# Mixed precision
mixed_precision: true

# Early stopping (0 = disabled)
early_stopping_patience: 0
early_stopping_min_delta: 0.0
