name: quick_test
steps: 200
batch_size: 16
seq_len: 128
optimizer: adamw
lr: 3e-4
weight_decay: 0.1
betas: [0.9, 0.95]
grad_clip: 1.0
warmup_steps: 20
lr_schedule: cosine
min_lr_ratio: 0.1
grad_accum_steps: 1
mixed_precision: false
early_stopping_patience: 0
early_stopping_min_delta: 0.01
